### DBND CI CD
### GENERAL CI CONFIG

### KNOWN ISSUES:
# `needs` doesn't work for failed job, the job after will run when the "needed" job is skipped
# A (fails) -> B (skip) -> C (runs!!!)

# default image to use
image: us.gcr.io/dbnd-dev-260010/databand/dbnd-ci-default:py310-latest-v1

stages:
  - test
  - build-base
  - publish
  - staging
  - test-windows
  - ci-utils

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  # Specific images according to a python version
  DOCKER_IMAGE_CI_PYTEST_PY37: us.gcr.io/dbnd-dev-260010/databand/dbnd-ci.test:py37-v2
  DOCKER_IMAGE_CI_PYTEST_PY39: us.gcr.io/dbnd-dev-260010/databand/dbnd-ci.test:py39-v2

### TESTS BASIC
.template__except_defaults:
  except: &except_on_skip_message
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

.template__on_every_commit:
  only: &on_every_commit
    - /^feature|fix/
    - master
    - merge_requests
    - develop
    - tags

.template__on_significant_branch_only:
  only: &on_significant_branch
    - master
    - merge_requests
    - develop
    - tags

### TEST TEMPLATES
.template__basic_job: &template__basic_checks_job
  stage: test
  only: *on_every_commit

.template__test_python: &template__python_test_job
  stage: test
  except: *except_on_skip_message

.template__test_python__cpu_heavy: &template__python_test_job__cpu_heavy
  <<: *template__python_test_job
  variables:
    KUBERNETES_CPU_REQUEST: 1200m
    KUBERNETES_CPU_LIMIT: 2000m
    KUBERNETES_MEMORY_REQUEST: 230Mi
    KUBERNETES_MEMORY_LIMIT: 1Gi


.template__test_windows: &template__windows_tests_job
  stage: test-windows
  only: *on_significant_branch
  except: *except_on_skip_message
  needs: ["empty_job"]
  before_script:
    - echo "start"
    - whoami
  tags:
    - windows
  # TODO: new models - sqlalchemy_utils.UUID - not wokring on windows?
  when: manual

empty_job:
  # workaround for gitlab not supporting empty `needs`
  # we want build jobs starting to run right away
  stage: test
  only: *on_significant_branch
  variables:
    KUBERNETES_CPU_REQUEST: 10m
    KUBERNETES_CPU_LIMIT: 100m
    KUBERNETES_MEMORY_REQUEST: 10Mi
    KUBERNETES_MEMORY_LIMIT: 100Mi
  script:
    - echo "Hello World"

pre_commit:
  <<: *template__python_test_job
  variables:
    KUBERNETES_CPU_REQUEST: 1200m
    KUBERNETES_CPU_LIMIT: 2000m
    KUBERNETES_MEMORY_REQUEST: 230Mi
    KUBERNETES_MEMORY_LIMIT: 1Gi
  image: ${DOCKER_IMAGE_CI_PYTEST_PY37}
  script:
    #    - tox -e pre-commit,docs,readme
    - tox -e pre-commit,bumpversion-check

lint:
  <<: *template__python_test_job__cpu_heavy
  image: ${DOCKER_IMAGE_CI_PYTEST_PY39}
  script:
    - tox -e lint,lint-tracking-airflow

manifest:
  <<: *template__python_test_job
  variables:
    KUBERNETES_CPU_REQUEST: 250m
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_MEMORY_REQUEST: 260Mi
    KUBERNETES_MEMORY_LIMIT: 1Gi
  image: ${DOCKER_IMAGE_CI_PYTEST_PY39}
  script:
    - make test-manifest

test dbnd py37:
  <<: *template__python_test_job
  image: ${DOCKER_IMAGE_CI_PYTEST_PY37}
  script:
    - cd modules/dbnd
    - tox -e py37
  artifacts:
    reports:
      junit: build/junit-py37.xml

test dbnd py39:
  <<: *template__python_test_job
  image: ${DOCKER_IMAGE_CI_PYTEST_PY39}
  script:
    - cd modules/dbnd
    - tox -e py39
  artifacts:
    reports:
      junit: build/junit-py39.xml

test dbnd_examples py39:
  <<: *template__python_test_job
  image: ${DOCKER_IMAGE_CI_PYTEST_PY39}
  script:
    - cd examples
    - tox -e py39
  artifacts:
    reports:
      junit: .tox/dbnd-examples/junit/junit-py39.xml

#dbnd_databricks_py37:
#  <<: *template__python_test_job
#  variables:
#    KUBERNETES_CPU_REQUEST: 900m
#    KUBERNETES_CPU_LIMIT: 2
#    KUBERNETES_MEMORY_REQUEST: 2.5Gi
#    KUBERNETES_MEMORY_LIMIT: 4Gi
#  image: python:3.7
#  script:
#    - cd plugins/dbnd-databricks
#    - tox -e py37
#  artifacts:
#    reports:
#      junit: plugins/dbnd-databricks/build/junit-py37.xml

dbnd_airflow 1_10_15_py37:
  <<: *template__python_test_job
  image: ${DOCKER_IMAGE_CI_PYTEST_PY37}
  script:
    - cd modules/dbnd-airflow
    - tox -e py37-airflow_1_10_15
  artifacts:
    reports:
      junit: modules/dbnd-airflow/build/junit-py37-airflow_1_10_15.xml
  only: *on_significant_branch

dbnd_airflow_monitor 1_10_10_py37:
  <<: *template__python_test_job
  image: ${DOCKER_IMAGE_CI_PYTEST_PY37}
  script:
    - cd modules/dbnd-airflow-monitor
    - tox -e py37-airflow_1_10_10
  artifacts:
    reports:
      junit: modules/dbnd-airflow-monitor/build/junit-py37-airflow_1_10_10.xml
  only: *on_significant_branch
  when: manual


build_pypi_org_whl:
  stage: build-base
  needs: ["empty_job"]
  script:
    - python setup.py sdist bdist_wheel
    - make dist-python
  artifacts:
    paths:
      - dist-python/*
  only:
    - tags
  when: manual
